/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ChatSession } from "./ChatSession";
import { ChatSessionCountArgs } from "./ChatSessionCountArgs";
import { ChatSessionFindManyArgs } from "./ChatSessionFindManyArgs";
import { ChatSessionFindUniqueArgs } from "./ChatSessionFindUniqueArgs";
import { DeleteChatSessionArgs } from "./DeleteChatSessionArgs";
import { ChatSessionService } from "../chatSession.service";
@graphql.Resolver(() => ChatSession)
export class ChatSessionResolverBase {
  constructor(protected readonly service: ChatSessionService) {}

  async _chatSessionsMeta(
    @graphql.Args() args: ChatSessionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ChatSession])
  async chatSessions(
    @graphql.Args() args: ChatSessionFindManyArgs
  ): Promise<ChatSession[]> {
    return this.service.chatSessions(args);
  }

  @graphql.Query(() => ChatSession, { nullable: true })
  async chatSession(
    @graphql.Args() args: ChatSessionFindUniqueArgs
  ): Promise<ChatSession | null> {
    const result = await this.service.chatSession(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ChatSession)
  async deleteChatSession(
    @graphql.Args() args: DeleteChatSessionArgs
  ): Promise<ChatSession | null> {
    try {
      return await this.service.deleteChatSession(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
