/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AdminConfig } from "./AdminConfig";
import { AdminConfigCountArgs } from "./AdminConfigCountArgs";
import { AdminConfigFindManyArgs } from "./AdminConfigFindManyArgs";
import { AdminConfigFindUniqueArgs } from "./AdminConfigFindUniqueArgs";
import { DeleteAdminConfigArgs } from "./DeleteAdminConfigArgs";
import { AdminConfigService } from "../adminConfig.service";
@graphql.Resolver(() => AdminConfig)
export class AdminConfigResolverBase {
  constructor(protected readonly service: AdminConfigService) {}

  async _adminConfigsMeta(
    @graphql.Args() args: AdminConfigCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AdminConfig])
  async adminConfigs(
    @graphql.Args() args: AdminConfigFindManyArgs
  ): Promise<AdminConfig[]> {
    return this.service.adminConfigs(args);
  }

  @graphql.Query(() => AdminConfig, { nullable: true })
  async adminConfig(
    @graphql.Args() args: AdminConfigFindUniqueArgs
  ): Promise<AdminConfig | null> {
    const result = await this.service.adminConfig(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AdminConfig)
  async deleteAdminConfig(
    @graphql.Args() args: DeleteAdminConfigArgs
  ): Promise<AdminConfig | null> {
    try {
      return await this.service.deleteAdminConfig(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
